export let top10HorrorMovies :string = `SELECT
FILM.TITLE AS MOVIE_NAME , CATEGORY.NAME AS MOVIE_CATEGORY , LANGUAGE.NAME AS MOVIE_LANGUAGE ,  CONCAT (ACTOR.FIRST_NAME , ' ', ACTOR.LAST_NAME) AS MOVIE_ACTOR
FROM CATEGORY
JOIN
FILM_CATEGORY
ON
CATEGORY.CATEGORY_ID = FILM_CATEGORY.CATEGORY_ID
JOIN
FILM
ON
FILM_CATEGORY.FILM_ID = FILM.FILM_ID
JOIN
LANGUAGE
ON
FILM.LANGUAGE_ID = LANGUAGE.LANGUAGE_ID
JOIN
FILM_ACTOR
ON
FILM.FILM_ID =FILM_ACTOR.FILM_ID
JOIN
ACTOR
ON
FILM_ACTOR.ACTOR_ID = ACTOR.ACTOR_ID
WHERE
CATEGORY.NAME = 'Horror'
AND
LANGUAGE.NAME = 'English'
AND
FILM.TITLE LIKE '%Devil%'
ORDER BY
FILM.TITLE ASC
LIMIT 10;
`;